CREATE TABLE lists(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

CREATE TABLE todos(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  list_id integer NOT NULL REFERENCES lists(id),
  completed boolean NOT NULL DEFAULT false
);
